checkout: git clone --recursive https://github.com/edwardstock/bigmath.git .

env:
  BINTRAY_USER: edwardstock
  BINTRAY_API_KEY: $ENV

commands:
  test:
    steps:
      - run: bash cfg/package_make.sh --test

  build_and_package:
    steps:
      - run: bash cfg/package_make.sh -t package
      - run: bash _build/package_upload.sh -t bintray

  make_project:
    steps:
      - test
      - build_and_package

  init_deb:
    steps:
      - run: apt -y install libmpdec-dev libgmp-dev

  init_centos:
    steps:
      - run: yum -y install gmp-devel mpdecimal-devel

  init_fedora:
    steps:
      - run: dnf -y update
      - run: dnf -y install mpir-devel mpdecimal-devel

jobs:
  centos7:
    image: docker.edwardstock.com/gcc_dev_el7:latest
    steps:
      - init_centos
      - make_project

  centos8:
    image: docker.edwardstock.com/gcc_dev_el8:latest
    steps:
      - init_centos
      - make_project

  fedora_fc32:
    image: docker.edwardstock.com/gcc_dev_fc32:latest
    steps:
      - init_fedora
      - make_project

  fedora_fc33:
    image: docker.edwardstock.com/gcc_dev_fc33:latest
    steps:
      - init_fedora
      - make_project

  fedora_fc34:
    image: docker.edwardstock.com/gcc_dev_fc34:latest
    steps:
      - init_fedora
      - make_project

  debian_jessie:
    image: docker.edwardstock.com/gcc_dev_debian_jessie:latest
    steps:
      - init_deb
      - make_project

  debian_stretch:
    image: docker.edwardstock.com/gcc_dev_debian_stretch:latest
    steps:
      - init_deb
      - make_project

  debian_buster:
    image: docker.edwardstock.com/gcc_dev_debian_buster:latest
    steps:
      - init_deb
      - make_project

  ubuntu_xenial:
    image: docker.edwardstock.com/gcc_dev_ubuntu_xenial:latest
    steps:
      - init_deb
      - make_project

  ubuntu_bionic:
    image: docker.edwardstock.com/gcc_dev_ubuntu_bionic:latest
    steps:
      - init_deb
      - make_project

  ubuntu_focal:
    image: docker.edwardstock.com/gcc_dev_ubuntu_focal:latest
    steps:
      - init_deb
      - make_project

  ubuntu_groovy:
    image: docker.edwardstock.com/gcc_dev_ubuntu_groovy:latest
    steps:
      - init_deb
      - make_project

